name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Add root directory to PATH
        run: export PATH=\$PATH:./django_glue

      - name: Testing
        run: python tests/manage.py test --settings=settings --noinput
